# Generated by Django 5.1.1 on 2025-01-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
