# Generated by Django 5.1.1 on 2025-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pincode',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
