# Generated by Django 5.1.1 on 2025-01-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_article_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
