# Generated by Django 5.1.1 on 2025-01-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
