# Generated by Django 5.1.1 on 2025-01-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_article_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='questions',
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.article')),
            ],
        ),
    ]
