# Generated by Django 5.1.6 on 2025-02-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_pagevisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='url',
            new_name='url_name',
        ),
    ]
