# Generated by Django 5.1.6 on 2025-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0012_urlmodel_delete_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='is_article',
            field=models.BooleanField(default=False),
        ),
    ]
