# Generated by Django 5.1.6 on 2025-03-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0015_remove_article_pincode_urlmodel_article_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
    ]
