# Generated by Django 5.1.6 on 2025-03-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0016_alter_article_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pincode',
            new_name='area',
        ),
    ]
