# Generated by Django 5.1.6 on 2025-04-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0019_remove_urlmodel_is_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processed_for_articles',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
