# Generated by Django 5.1.6 on 2025-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0020_post_processed_for_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='processed_for_articles',
        ),
        migrations.AddField(
            model_name='area',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='areas', to='news_app.article'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='areas', to='news_app.post'),
        ),
    ]
