# Generated by Django 5.1.6 on 2025-04-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0021_remove_post_processed_for_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
