# Generated by Django 5.1.5 on 2025-04-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0023_migrate_area_normalization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="display_name",
        ),
    ]
