# Generated by Django 5.1.6 on 2025-09-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0025_remove_area_articles_remove_area_posts_article_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='reporter_name',
            field=models.CharField(blank=True, help_text="Displayed under the article title. Can be a name or a generic credit like 'Community Reports'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(default='general', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='news_app.area')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
