# Generated by Django 5.1.6 on 2025-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0026_article_likes_article_reporter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
