# Generated by Django 5.1.6 on 2025-09-13 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0027_advertisement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['display_name']},
        ),
        migrations.AddField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('neighborhood', 'Neighborhood'), ('city', 'City'), ('district', 'District'), ('suburb', 'Suburb'), ('village', 'Village'), ('custom', 'Custom Area')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='area',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='created_by_user',
            field=models.BooleanField(default=False, help_text='True if created by user input'),
        ),
        migrations.AddField(
            model_name='area',
            name='display_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Formatted name for display', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='area',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='state_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='area',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='area',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
