# Generated by Django 5.1.6 on 2025-09-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0028_alter_area_options_area_area_type_area_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='display_name',
            field=models.CharField(blank=True, help_text='Formatted name for display', max_length=255),
        ),
    ]
