# Generated by Django 5.1.6 on 2025-09-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0029_alter_area_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='area',
            name='country',
        ),
        migrations.RemoveField(
            model_name='area',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='area',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='area',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='area',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='area',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='area',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='area',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='area',
            name='verification_status',
        ),
        migrations.AlterField(
            model_name='area',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
