# Generated by Django 5.1.6 on 2025-09-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0031_notificationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('p256dh', models.CharField(blank=True, max_length=255, null=True)),
                ('auth', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, help_text='Optional device/user label', max_length=200, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='news_app.area')),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationSubscription',
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['area'], name='news_app_pu_area_id_ab2949_idx'),
        ),
    ]
